# fly.toml app configuration file generated for uh-fullstackopen-part11-pokedex on 2023-12-22T01:38:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uh-fullstackopen-part11-pokedex"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
