# fly.toml app configuration file generated for uh-fullstackopen-part11-pokedex on 2023-12-22T01:38:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uh-fullstackopen-part11-pokedex"
primary_region = "ams"

[build]

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 5000

[[services.http_checks]]
  grace_period = "5s"
  interval = "15s"
  method = "get"
  path = "/healthz"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
