name: Deployment pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies 
        run: npm ci  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test (Jest)
        run: npm run test
      - name: Test (Cypress)
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy (Fly.io)
        id: deploy
        if: >-
          ${{ github.event_name == 'push' &&
            !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Discord webhook (deploy)
        if: ${{ steps.deploy.outcome == 'success' }}
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        with:
            description: Commit [${{ github.event.head }}](https://github.com/${{ github.repository }}/commit/${{ github.event.head }}) built and deployed!
            footer: Triggered by ${{ github.event.actor.login }}
            severity: info
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Discord webhook (failure)
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ failure() }}
        with:
            description: Pipeline failed for commit [${{ github.event.head }}](https://github.com/${{ github.repository }}/commit/${{ github.event.head }}).
            footer: Triggered by ${{ github.event.actor.login }}
            severity: error
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
  tag_release:
    needs: [simple_deployment_pipeline]
    if: >-
      ${{ github.event_name == 'push' &&
        !contains(join(github.event.commits.*.message, ' '), '#skip') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version number and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
